name = "testdocs"
uuid = "e7465386-84a2-43ab-8714-da45e5fcface"
authors = ["kfgarrity <kevin.garrity@nist.gov> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
